// <auto-generated />

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using SwissBank.Data.Models;

namespace SwissBank.Data.Migrations
{
    [DbContext(typeof(SwissBankDbContext))]
    partial class SwissBankDbContext : DbContext
    {

        public virtual DbSet<Account> Schools { get; set; }


        public SwissBankDbContext(DbContextOptions<SwissBankDbContext> options) : base(options)
        {

        }

        protected void BuildModel(ModelBuilder modelBuilder)
        {
            
        }
    }
}
